# App Deployment

# This workflow is used to deploy the app to the Hugging Face hub.

# The workflow is triggered by a push to the repository in the following paths:
# - app/**

# If the tests pass, the app is deployed to the Hugging Face hub.

name: App Deployment

on:
  push:
    paths:
      - "app/**"
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/app/test_model.py

      - name: Push to hub
        if: success()
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://0xfedev:$HF_TOKEN@huggingface.co/spaces/0xfedev/corporate-sentiment-monitoring main
