# Model Evaluation, Retraining and Deployment

# This workflow is used to evaluate the model, retrain it if the accuracy is not good enough and deploy the new model.

# The workflow is triggered by a push to the repository in the following paths:
# - data/**
# - lib/**
# - model/**

name: Model Retraining and Deployment

on:
  push:
    paths:
      - "data/**"
      - "lib/**"
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  training:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Train script
        run: python ./lib/train.py --trainset ./data/train.csv --validationset ./data/validation.csv --metrics ./metrics/base_metrics.json --model ./model
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Commit new metrics
        if: ${{ success() }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./metrics/new_metrics.json
          git commit -m "Update metrics after training"
          git push
