# Model Monitoring

# This workflow is used to monitor the model and trigger the retraining if the accuracy is not good enough.

# The workflow is triggered by a schedule or manually by the user.

name: Model Monitoring

on:
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  monitoring:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Evaluation script
        run: python ./lib/evaluate_model.py --metrics ./metrics/base_metrics.json

      - name: Commit new dataset
        if: ${{ success() }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./data/train.csv
          git commit -m "Update train dataset"
          git push

      - name: Trigger training workflow
        if: ${{ success() }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: Fede91/ml-monitoring-project
          workflow: model.yml
          ref: main
